import Link from "next/link";
import { notFound,redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { SupportReplyForm } from "@/components/support/SupportReplyForm";

export default async function SupportTicketPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect(`/login?next=/support/${id}`);
 const[{data:ticket},{data:messages}]=await Promise.all([supabase.from("support_tickets").select("id,ticket_number,subject,description,category,priority,status,source_route,created_at,updated_at").eq("id",id).eq("created_by",user.id).maybeSingle(),supabase.from("support_messages").select("id,sender_id,sender_role,body,created_at").eq("ticket_id",id).order("created_at")]);if(!ticket)notFound();
 return <main className="container-shell max-w-4xl py-10"><Link className="text-sm font-bold text-brand-700" href="/support">← My Support Requests</Link><section className="card mt-4 p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-bold text-brand-700">{ticket.ticket_number}</p><h1 className="mt-1 text-2xl font-black">{ticket.subject}</h1><p className="mt-2 text-sm capitalize text-slate-600">{ticket.category.replaceAll("_"," ")} · {ticket.priority} priority</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-sm font-bold capitalize">{ticket.status.replaceAll("_"," ")}</span></div>{ticket.category==="payments"&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-950">BuildMate orders are currently Cash on Delivery. Do not make advance payment outside the approved BuildMate order process.</p>}</section><section className="mt-6 space-y-3" aria-label="Support conversation">{(messages??[]).map(message=><article className={`max-w-[88%] rounded-2xl p-4 ${message.sender_id===user.id?"ml-auto bg-brand-700 text-white":"bg-white shadow"}`} key={message.id}><p className="text-xs font-bold capitalize opacity-70">{message.sender_id===user.id?"You":"BuildMate Support"}</p><p className="mt-2 whitespace-pre-wrap text-sm">{message.body}</p><p className="mt-2 text-[11px] opacity-70">{new Date(message.created_at).toLocaleString("en-GH")}</p></article>)}</section>{ticket.status!=="closed"?<SupportReplyForm ticketId={ticket.id}/>:<p className="card mt-5 p-5 text-sm text-slate-600">This ticket is closed.</p>}</main>;
}
