import Link from "next/link";
import {DashboardShell}from"@/components/dashboard/DashboardShell";
import {InventoryOperationForms}from"@/components/supplier/inventory/InventoryOperationForms";
import {ReturnProcessing}from"@/components/supplier/inventory/ReturnProcessing";
import {requireSupplierPermission}from"@/lib/organisations/access";import{supplierNavigation}from"@/lib/organisations/navigation";
type Row={listing_id:string;product:string;variant:string|null;sku:string|null;category:string|null;brand:string|null;branch:string|null;warehouse:string|null;inventory_mode:string;on_hand:number|null;reserved:number|null;available:number|null;sold:number|null;damaged:number|null;average_cost:number|null;selling_price:number|null;cost_value:number|null;selling_value:number|null;stock_status:string;reorder_point:number|null;last_movement_at:string|null;updated_at:string;sales_velocity:number};
type Dashboard={can_view_cost:boolean;summary:{total_skus:number;on_hand:number;available:number;reserved:number;cost_value:number|null;retail_value:number;potential_margin:number|null;low_stock:number;out_of_stock:number;confirmation_required:number};rows:Row[]};
const money=(value:number|null)=>value==null?"Restricted":`GHS ${Number(value).toFixed(2)}`;const values=(rows:Row[],key:keyof Row)=>[...new Set(rows.map(r=>String(r[key]??"")).filter(Boolean))].sort();
export default async function SupplierInventoryPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const q=await searchParams,{supabase,membership}=await requireSupplierPermission("inventory.view");const[{data},{data:listings},{data:returns},{data:receive},{data:adjust},{data:transfer},{data:configure}]=await Promise.all([supabase.rpc("inventory_dashboard",{target_organisation:membership.organisationId}),supabase.from("supplier_listings").select("id,products(name),product_variants(name),supplier_branches(name),supplier_warehouses(name)").eq("supplier_id",membership.organisationId).order("created_at"),supabase.rpc("inventory_return_queue",{target_organisation:membership.organisationId}),...(["inventory.receive","inventory.adjust","inventory.transfer","inventory.configure"].map(target_permission=>supabase.rpc("has_permission",{target_permission,target_organisation:membership.organisationId})))]);
 const dashboard=(data??{can_view_cost:false,summary:{},rows:[]})as Dashboard,s=dashboard.summary,search=(q.search??"").toLowerCase();let rows=dashboard.rows.filter(r=>(!search||`${r.product} ${r.sku??""}`.toLowerCase().includes(search))&&(!q.category||r.category===q.category)&&(!q.brand||r.brand===q.brand)&&(!q.branch||r.branch===q.branch)&&(!q.warehouse||r.warehouse===q.warehouse)&&(!q.mode||r.inventory_mode===q.mode)&&(!q.status||r.stock_status===q.status)&&(!q.updated||r.updated_at?.slice(0,10)>=q.updated));
 const direction=q.direction==="desc"?-1:1,sort=q.sort??"product";rows=rows.sort((a,b)=>direction*(sort==="product"?a.product.localeCompare(b.product):Number((a[sort as keyof Row]??0))-Number((b[sort as keyof Row]??0))));
 const options=(listings??[]).map(l=>{const p=l.products as unknown as{name:string}|null,v=l.product_variants as unknown as{name:string}|null,b=l.supplier_branches as unknown as{name:string}|null,w=l.supplier_warehouses as unknown as{name:string}|null;return{id:l.id,label:`${p?.name??"Product"}${v?` — ${v.name}`:""} · ${b?.name??"No branch"}${w?` / ${w.name}`:""}`}});
 const cards=[["Total SKUs",s.total_skus],["On hand",s.on_hand],["Available",s.available],["Reserved",s.reserved],["Stock cost value",money(s.cost_value)],["Potential sales value",money(s.retail_value)],["Potential gross margin",money(s.potential_margin)],["Low / out of stock",`${s.low_stock} / ${s.out_of_stock}`],["Needs confirmation",s.confirmation_required]];
 return <DashboardShell title="Supplier portal" nav={await supplierNavigation(membership.organisationId)}><h1 className="text-3xl font-black">Inventory control</h1><p className="mt-2 text-slate-600">Movement-backed stock, reservations and weighted-average valuation.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label,value])=><div className="card p-4" key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value??0}</p></div>)}</div><InventoryOperationForms listings={options} canReceive={receive===true} canAdjust={adjust===true} canTransfer={transfer===true} canConfigure={configure===true}/><ReturnProcessing items={(returns??[]) as never[]}/>
 <form className="card mt-6 grid gap-3 p-4 md:grid-cols-4 xl:grid-cols-6"><input className="input" name="search" defaultValue={q.search} placeholder="Product or SKU"/><Select name="category" label="Category" current={q.category} options={values(dashboard.rows,"category")}/><Select name="brand" label="Brand" current={q.brand} options={values(dashboard.rows,"brand")}/><Select name="branch" label="Branch" current={q.branch} options={values(dashboard.rows,"branch")}/><Select name="warehouse" label="Warehouse" current={q.warehouse} options={values(dashboard.rows,"warehouse")}/><Select name="mode" label="Inventory mode" current={q.mode} options={values(dashboard.rows,"inventory_mode")}/><Select name="status" label="Stock status" current={q.status} options={values(dashboard.rows,"stock_status")}/><label><span className="label">Updated since</span><input className="input" type="date" name="updated" defaultValue={q.updated}/></label><Select name="sort" label="Sort" current={sort} options={["product","available","cost_value","selling_value","last_movement_at","sales_velocity"]}/><Select name="direction" label="Direction" current={q.direction??"asc"} options={["asc","desc"]}/><button className="btn-primary self-end">Apply filters</button><Link className="btn-secondary self-end text-center" href="/supplier/inventory">Clear</Link></form>
 <section className="card mt-6 overflow-x-auto"><table className="w-full min-w-[1500px] text-left text-sm"><thead><tr className="border-b"><th className="p-4">Product</th><th>Location</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Sold</th><th>Damaged</th><th>Cost</th><th>Selling price</th><th>Cost value</th><th>Selling value</th><th>Status</th><th>Reorder</th><th>Last movement</th></tr></thead><tbody>{rows.map(r=><tr className="border-b last:border-0" key={`${r.listing_id}-${r.branch}-${r.warehouse}`}><td className="p-4"><Link className="font-bold text-brand-700" href={`/supplier/inventory/${r.listing_id}`}>{r.product}</Link><p className="text-xs text-slate-500">{r.variant??"Standard"} · {r.sku??"No SKU"}</p></td><td>{r.branch??"Unassigned"}{r.warehouse?` / ${r.warehouse}`:""}</td><td>{r.on_hand??"—"}</td><td>{r.reserved??"—"}</td><td>{r.available??"—"}</td><td>{r.sold??"—"}</td><td>{r.damaged??"—"}</td><td>{money(r.average_cost)}</td><td>{money(r.selling_price)}</td><td>{money(r.cost_value)}</td><td>{money(r.selling_value)}</td><td className="capitalize">{r.stock_status.replaceAll("_"," ")}</td><td>{r.reorder_point??"—"}</td><td>{r.last_movement_at?new Date(r.last_movement_at).toLocaleDateString("en-GH"):"None"}</td></tr>)}{!rows.length&&<tr><td colSpan={14} className="p-8 text-center text-slate-500">No inventory matches these filters.</td></tr>}</tbody></table></section></DashboardShell>;
}
function Select({name,label,current,options}:{name:string;label:string;current?:string;options:string[]}){return <label><span className="label">{label}</span><select className="input" name={name} defaultValue={current??""}><option value="">All</option>{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
