import Link from "next/link";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { requireSupplierPermission } from "@/lib/organisations/access";
import { supplierNavigation } from "@/lib/organisations/navigation";
type Movement={id:string;movement_type:string;quantity:number;unit_cost:number|null;previous_on_hand:number;resulting_on_hand:number;previous_reserved:number;resulting_reserved:number;reference_type:string|null;reason:string;created_by:string|null;created_at:string};
type Position={on_hand:number|null;reserved:number|null;available:number|null;sold:number|null;damaged:number|null;lost:number|null;returned:number|null;average_cost:number|null;selling_price:number|null;cost_value:number|null;selling_value:number|null;potential_margin:number|null;reorder_point:number|null;last_movement:string|null};
type Price={id:number;previous_price:number|null;new_price:number;currency:string;effective_date:string;source:string;created_at:string;profiles:{full_name:string|null}|{full_name:string|null}[]|null};
const money=(value:number|null)=>value==null?"Not available":`GHS ${Number(value).toFixed(2)}`;
const metric=(value:number|null)=>value==null?"Not tracked":String(value);
export default async function InventoryDetail({params}:{params:Promise<{listingId:string}>}){
 const{listingId}=await params;if(!/^[0-9a-f-]{36}$/i.test(listingId))notFound();const{supabase,membership}=await requireSupplierPermission("inventory.view");
 const[{data:listing},{data:history},{data:position},{data:prices}]=await Promise.all([supabase.from("supplier_listings").select("id,price,products(name),product_variants(name)").eq("id",listingId).eq("supplier_id",membership.organisationId).maybeSingle(),supabase.rpc("inventory_movement_history",{target_listing:listingId}),supabase.rpc("inventory_listing_position",{target_listing:listingId}),supabase.from("supplier_price_history").select("id,previous_price,new_price,currency,effective_date,source,created_at,profiles!supplier_price_history_changed_by_fkey(full_name)").eq("supplier_listing_id",listingId).order("created_at",{ascending:false})]);
 if(!listing)notFound();const p=listing.products as unknown as{name:string}|null,v=listing.product_variants as unknown as{name:string}|null;const rows=(history??[]) as Movement[],current=(position??{}) as Position,priceRows=(prices??[]) as Price[];
 const quantityCards=[["on_hand","On hand"],["reserved","Reserved"],["available","Available"],["sold","Sold"],["damaged","Damaged"],["lost","Lost"],["returned","Returned"]].map(([key,label])=>[label,metric(current[key as keyof Position] as number|null)]);
 const valueCards=["average_cost","selling_price","cost_value","selling_value","potential_margin"].map(key=>[key.replaceAll("_"," "),money(current[key as keyof Position] as number|null)]);
 const cards=[...quantityCards,...valueCards,["Reorder level",metric(current.reorder_point)],["Last movement",current.last_movement?new Date(current.last_movement).toLocaleString("en-GH"):"No movements"]];
 return <DashboardShell title="Supplier portal" nav={await supplierNavigation(membership.organisationId)}><Link className="font-semibold text-brand-700" href="/supplier/inventory">← Inventory</Link><h1 className="mt-3 text-3xl font-black">{p?.name}{v?` — ${v.name}`:""}</h1><p className="mt-2 text-slate-600">Append-only stock history. Corrections are compensating movements.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value])=><div className="card p-4" key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>)}</div>
 <section className="card mt-6 overflow-x-auto"><div className="p-5"><h2 className="text-xl font-bold">Price history</h2><p className="text-sm text-slate-600">Append-only history of supplier price changes.</p></div><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b"><th className="p-4">Effective date</th><th>Previous</th><th>New</th><th>Source</th><th>Changed by</th><th>Recorded</th></tr></thead><tbody>{priceRows.map(x=>{const actor=Array.isArray(x.profiles)?x.profiles[0]:x.profiles;return <tr className="border-b last:border-0" key={x.id}><td className="p-4">{x.effective_date}</td><td>{x.previous_price==null?"Initial price":`${x.currency} ${Number(x.previous_price).toFixed(2)}`}</td><td className="font-bold">{x.currency} {Number(x.new_price).toFixed(2)}</td><td>{x.source}</td><td>{actor?.full_name??"System"}</td><td>{new Date(x.created_at).toLocaleString("en-GH")}</td></tr>})}{!priceRows.length&&<tr><td className="p-8 text-center text-slate-500" colSpan={6}>No price changes recorded.</td></tr>}</tbody></table></section>
 <section className="card mt-6 overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr className="border-b"><th className="p-4">Date</th><th>Movement</th><th>Quantity</th><th>On hand</th><th>Reserved</th><th>Unit cost</th><th>Reference</th><th>Actor / reason</th></tr></thead><tbody>{rows.map(m=><tr className="border-b last:border-0" key={m.id}><td className="p-4">{new Date(m.created_at).toLocaleString("en-GH")}</td><td className="capitalize">{m.movement_type.replaceAll("_"," ")}</td><td>{m.quantity}</td><td>{m.previous_on_hand} → {m.resulting_on_hand}</td><td>{m.previous_reserved} → {m.resulting_reserved}</td><td>{money(m.unit_cost)}</td><td>{m.reference_type??"—"}</td><td>{m.created_by??"System"}<p className="text-xs text-slate-500">{m.reason}</p></td></tr>)}{!rows.length&&<tr><td className="p-8 text-center text-slate-500" colSpan={8}>No inventory movements yet.</td></tr>}</tbody></table></section></DashboardShell>;
}
