export const ADMIN_NAV = [
  { label: "Overview", href: "/admin" },
  {
    label: "Customers",
    href: "/admin/customers",
    children: [
      { label: "All Customers", href: "/admin/customers" },
      { label: "Contractors", href: "/admin/customers?type=contractor" },
      { label: "Organisations", href: "/admin/organisations" },
      { label: "Suspended Accounts", href: "/admin/customers?status=suspended" },
    ],
  },
  {
    label: "Suppliers",
    href: "/admin/suppliers",
    children: [
      { label: "All Suppliers", href: "/admin/suppliers" },
      { label: "Applications", href: "/admin/supplier-applications" },
      { label: "Approved", href: "/admin/suppliers?status=approved" },
      { label: "Suspended", href: "/admin/suppliers?status=suspended" },
      { label: "Performance", href: "/admin/suppliers?sort=highest_sales" },
    ],
  },
  { label: "Products", href: "/admin/catalogue" },
  { label: "Quotations", href: "/admin/quotations" },
  { label: "Orders", href: "/admin/orders" },
  { label: "Deliveries", href: "/admin/deliveries" },
  { label: "Service Providers", href: "/admin/service-providers" },
  { label: "Payments", href: "/admin/payments" },
  { label: "Settlements", href: "/admin/settlements" },
  { label: "Disputes", href: "/admin/disputes" },
  {
    label: "Support",
    href: "/admin/support",
    children: [
      { label: "Inbox", href: "/admin/support" },
      { label: "Unassigned", href: "/admin/support?filter=unassigned" },
      { label: "Open", href: "/admin/support?filter=open" },
      { label: "Assigned to me", href: "/admin/support?filter=mine" },
      { label: "Awaiting user", href: "/admin/support?filter=awaiting_user" },
      { label: "Resolved", href: "/admin/support?filter=resolved" },
      { label: "Closed", href: "/admin/support?filter=closed" },
    ],
  },
  { label: "Reports", href: "/admin/reports" },
  { label: "Audit Logs", href: "/admin/audit-logs" },
  { label: "Security & Operations", href: "/admin/security" },
  { label: "Staff", href: "/admin/staff" },
  { label: "Online Users", href: "/admin/online-users" },
  { label: "Settings", href: "/admin/settings" },
] as const;
