"use client";

import { useActionState } from "react";
import { adjustStock, configureInventory, receiveStock, transferStock, type InventoryActionState } from "@/app/supplier/inventory/actions";

type ListingOption={id:string;label:string};
const initial:InventoryActionState={};
function Status({state}:{state:InventoryActionState}){return state.error?<p className="mt-3 text-sm font-semibold text-red-700">{state.error}</p>:state.message?<p className="mt-3 text-sm font-semibold text-emerald-700">{state.message}</p>:null}
function ListingSelect({name,listings}:{name:string;listings:ListingOption[]}){return <select className="input" name={name} required><option value="">Choose product</option>{listings.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select>}

export function InventoryOperationForms({listings,canReceive,canAdjust,canTransfer,canConfigure}:{listings:ListingOption[];canReceive:boolean;canAdjust:boolean;canTransfer:boolean;canConfigure:boolean}){
 const[receiveState,receiveAction,receivePending]=useActionState(receiveStock,initial);const[adjustState,adjustAction,adjustPending]=useActionState(adjustStock,initial);const[transferState,transferAction,transferPending]=useActionState(transferStock,initial);const[configState,configAction,configPending]=useActionState(configureInventory,initial);
 return <div className="mt-6 grid gap-5 lg:grid-cols-2">
  {canReceive&&<form action={receiveAction} className="card p-5"><h2 className="text-xl font-bold">Receive stock</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Product</span><ListingSelect name="listingId" listings={listings}/></label><label><span className="label">Quantity</span><input className="input" name="quantity" type="number" min="0.01" step="0.01" required/></label><label><span className="label">Unit cost (GHS)</span><input className="input" name="unitCost" type="number" min="0" step="0.01" required/></label><label><span className="label">Vendor</span><input className="input" name="vendor"/></label><label><span className="label">Invoice/reference</span><input className="input" name="invoice"/></label><label><span className="label">Received date</span><input className="input" name="receivedDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label><span className="label">Notes</span><input className="input" name="notes"/></label></div><button className="btn-primary mt-4" disabled={receivePending}>{receivePending?"Recording…":"Receive stock"}</button><Status state={receiveState}/></form>}
  {canAdjust&&<form action={adjustAction} className="card p-5"><h2 className="text-xl font-bold">Adjust stock</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Product</span><ListingSelect name="listingId" listings={listings}/></label><label><span className="label">Movement</span><select className="input" name="movementType"><option value="stock_adjustment_positive">Increase</option><option value="stock_adjustment_negative">Decrease</option><option value="damaged">Damaged</option><option value="lost">Lost</option><option value="stock_count_correction">Stock-count correction (+)</option></select></label><label><span className="label">Quantity</span><input className="input" name="quantity" type="number" min="0.01" step="0.01" required/></label><label><span className="label">Reason</span><input className="input" name="reason" minLength={5} required/></label><label><span className="label">Notes</span><input className="input" name="notes"/></label></div><button className="btn-primary mt-4" disabled={adjustPending}>{adjustPending?"Recording…":"Record adjustment"}</button><Status state={adjustState}/></form>}
  {canTransfer&&<form action={transferAction} className="card p-5"><h2 className="text-xl font-bold">Transfer stock</h2><p className="mt-1 text-sm text-slate-600">Source and destination must be location-specific listings for the same product and variant.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="label">Source</span><ListingSelect name="sourceListing" listings={listings}/></label><label><span className="label">Destination</span><ListingSelect name="destinationListing" listings={listings}/></label><label><span className="label">Quantity</span><input className="input" name="quantity" type="number" min="0.01" step="0.01" required/></label><label><span className="label">Reason</span><input className="input" name="reason" minLength={5} required/></label></div><button className="btn-primary mt-4" disabled={transferPending}>{transferPending?"Transferring…":"Transfer"}</button><Status state={transferState}/></form>}
  {canConfigure&&<form action={configAction} className="card p-5"><h2 className="text-xl font-bold">Inventory settings</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Product</span><ListingSelect name="listingId" listings={listings}/></label><label><span className="label">Mode</span><select className="input" name="inventoryMode"><option value="confirmation_required">Confirmation required</option><option value="status_only">Status only</option><option value="exact_quantity">Exact quantity</option></select></label><label className="flex items-center gap-2 pt-7"><input type="checkbox" name="showExact"/>Show exact stock to customers</label><label><span className="label">Reorder point</span><input className="input" name="reorderPoint" type="number" min="0" step="0.01"/></label><label><span className="label">Preferred reorder quantity</span><input className="input" name="preferredReorder" type="number" min="0.01" step="0.01"/></label></div><button className="btn-primary mt-4" disabled={configPending}>{configPending?"Saving…":"Save settings"}</button><Status state={configState}/></form>}
 </div>
}
