import Link from "next/link";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { SupportReplyForm } from "@/components/support/SupportReplyForm";
import { ADMIN_NAV } from "@/lib/admin/navigation";
import { createClient } from "@/lib/supabase/server";
import { updateSupportTicket } from "@/app/support/actions";

const categories=["shopping_products","quotations","orders","payments","delivery","returns_refunds","supplier_support","driver_support","service_provider_support","account_login","technical_problem"];
export default async function AdminSupportTicketPage({params}:{params:Promise<{id:string}>}){const{id}=await params,supabase=await createClient();const[{data:ticket},{data:messages},{data:staff}]=await Promise.all([supabase.from("support_tickets").select("*,profiles!support_tickets_created_by_fkey(full_name,phone),organisations(name),orders(order_number),deliveries(id),quote_requests(title),service_requests(request_number)").eq("id",id).maybeSingle(),supabase.from("support_messages").select("id,sender_id,sender_role,body,internal_note,created_at,profiles(full_name)").eq("ticket_id",id).order("created_at"),supabase.from("platform_staff_memberships").select("user_id,profiles(full_name)").eq("status","active")]);if(!ticket)notFound();const requester=ticket.profiles as unknown as{full_name:string|null;phone:string|null}|null;
 return <DashboardShell title="Platform administration" nav={[...ADMIN_NAV]}><Link className="text-sm font-bold text-brand-700" href="/admin/support">← Support queue</Link><div className="mt-4 grid gap-6 xl:grid-cols-[1fr_320px]"><div><section className="card p-6"><p className="text-sm font-bold text-brand-700">{ticket.ticket_number}</p><h1 className="mt-1 text-2xl font-black">{ticket.subject}</h1><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><b>Requester:</b> {requester?.full_name??"User"}</p><p><b>Role:</b> {ticket.requester_role.replaceAll("_"," ")}</p><p><b>Organisation:</b> {(ticket.organisations as unknown as{name:string}|null)?.name??"—"}</p><p><b>Created:</b> {new Date(ticket.created_at).toLocaleString("en-GH")}</p><p><b>Source:</b> {ticket.source_route??"Not captured"}</p><Related ticket={ticket}/></div></section><section className="mt-5 space-y-3">{(messages??[]).map(message=><article className={`rounded-2xl p-4 ${message.internal_note?"border border-amber-300 bg-amber-50":"card"}`} key={message.id}><div className="flex justify-between gap-3"><b>{message.internal_note?"Internal note":message.sender_role.replaceAll("_"," ")}</b><span className="text-xs text-slate-500">{new Date(message.created_at).toLocaleString("en-GH")}</span></div><p className="mt-2 whitespace-pre-wrap text-sm">{message.body}</p></article>)}</section>{ticket.status!=="closed"&&<SupportReplyForm ticketId={ticket.id} allowInternal/>}</div><aside><form action={updateSupportTicket} className="card p-5"><h2 className="text-lg font-black">Ticket controls</h2><input type="hidden" name="ticketId" value={ticket.id}/><label className="mt-4 block"><span className="label">Status</span><select className="input" name="status" defaultValue={ticket.status}>{["open","in_progress","awaiting_user","resolved","closed"].map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="mt-3 block"><span className="label">Priority</span><select className="input" name="priority" defaultValue={ticket.priority}>{["low","normal","high","urgent"].map(x=><option value={x} key={x}>{x}</option>)}</select></label><label className="mt-3 block"><span className="label">Category</span><select className="input" name="category" defaultValue={ticket.category}>{categories.map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="mt-3 block"><span className="label">Assigned admin</span><select className="input" name="assignedTo" defaultValue={ticket.assigned_to??""}><option value="">Unassigned</option>{(staff??[]).map(member=><option value={member.user_id} key={member.user_id}>{(member.profiles as unknown as{full_name:string}|null)?.full_name??member.user_id}</option>)}</select></label><button className="btn-primary mt-4 w-full">Save ticket</button></form></aside></div></DashboardShell>;
}
function Related({ticket}:{ticket:Record<string,unknown>}){const order=ticket.orders as{order_number:string}|null,request=ticket.service_requests as{request_number:string}|null;if(order)return <p><b>Related order:</b> <Link className="text-brand-700" href="/admin/orders">{order.order_number}</Link></p>;if(ticket.related_delivery_id)return <p><b>Related delivery:</b> <Link className="text-brand-700" href="/admin/deliveries">View delivery</Link></p>;if(ticket.related_quote_id)return <p><b>Related quotation:</b> <Link className="text-brand-700" href="/admin/quotations">View quotation</Link></p>;if(request)return <p><b>Service request:</b> {request.request_number}</p>;return <p><b>Related record:</b> —</p>;}
