import Link from "next/link";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { ADMIN_NAV } from "@/lib/admin/navigation";
import { createClient } from "@/lib/supabase/server";

type Ticket={id:string;ticket_number:string;requester_role:string;category:string;subject:string;priority:string;status:string;assigned_to:string|null;created_at:string;updated_at:string;profiles:{full_name:string|null}|null;organisations:{name:string}|null};
export default async function AdminSupportPage({searchParams}:{searchParams:Promise<{filter?:string}>}){
 const{filter}=await searchParams,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();let query=supabase.from("support_tickets").select("id,ticket_number,requester_role,category,subject,priority,status,assigned_to,created_at,updated_at,profiles!support_tickets_created_by_fkey(full_name),organisations(name)").order("updated_at",{ascending:false}).limit(100);
 if(filter==="unassigned")query=query.is("assigned_to",null).in("status",["open","in_progress"]);else if(filter==="mine"&&user)query=query.eq("assigned_to",user.id);else if(filter&&["open","awaiting_user","resolved","closed"].includes(filter))query=query.eq("status",filter);
 if(filter==="urgent")query=query.eq("priority","urgent").in("status",["open","in_progress"]);
 const today=new Date();today.setHours(0,0,0,0);
 const[{data,error},{count:open},{count:urgent},{count:unassigned},{count:awaiting},{count:awaitingUser},{count:resolvedToday}]=await Promise.all([query,supabase.from("support_tickets").select("id",{count:"exact",head:true}).in("status",["open","in_progress"]),supabase.from("support_tickets").select("id",{count:"exact",head:true}).eq("priority","urgent").not("status","in",'(resolved,closed)'),supabase.from("support_tickets").select("id",{count:"exact",head:true}).is("assigned_to",null).in("status",["open","in_progress"]),supabase.from("support_tickets").select("id",{count:"exact",head:true}).eq("status","open"),supabase.from("support_tickets").select("id",{count:"exact",head:true}).eq("status","awaiting_user"),supabase.from("support_tickets").select("id",{count:"exact",head:true}).gte("resolved_at",today.toISOString())]);
 const cards=[["Open tickets",open??0,"open"],["Urgent",urgent??0,"urgent"],["Unassigned",unassigned??0,"unassigned"],["Awaiting admin response",awaiting??0,"open"],["Awaiting user",awaitingUser??0,"awaiting_user"],["Resolved today",resolvedToday??0,"resolved"]] as const;
 return <DashboardShell title="Platform administration" nav={[...ADMIN_NAV]}><h1 className="text-3xl font-black">Support</h1><p className="mt-2 text-slate-600">Triage, assign and resolve BuildMate support requests.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,target])=><Link className="card p-4" href={`/admin/support?filter=${target}`} key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></Link>)}</div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">Unable to load support queue: {error.message}</p>}<div className="card mt-6 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead><tr className="border-b"><th className="p-4">Ticket</th><th>Requester</th><th>Role</th><th>Organisation</th><th>Category / Subject</th><th>Priority</th><th>Status</th><th>Last activity</th><th>Age</th><th/></tr></thead><tbody>{((data??[]) as unknown as Ticket[]).map(ticket=><tr className="border-b" key={ticket.id}><td className="p-4 font-bold">{ticket.ticket_number}</td><td>{ticket.profiles?.full_name??"User"}</td><td className="capitalize">{ticket.requester_role.replaceAll("_"," ")}</td><td>{ticket.organisations?.name??"—"}</td><td><b className="capitalize">{ticket.category.replaceAll("_"," ")}</b><p className="max-w-64 truncate text-xs text-slate-500">{ticket.subject}</p></td><td className="capitalize">{ticket.priority}</td><td className="capitalize">{ticket.status.replaceAll("_"," ")}</td><td>{new Date(ticket.updated_at).toLocaleString("en-GH")}</td><td>{age(ticket.created_at)}</td><td><Link className="font-bold text-brand-700" href={`/admin/support/${ticket.id}`}>Open</Link></td></tr>)}{!data?.length&&!error&&<tr><td colSpan={10} className="p-8 text-center text-slate-500">No support tickets match this queue.</td></tr>}</tbody></table></div></DashboardShell>;
}
function age(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<60)return`${minutes} min`;if(minutes<1440)return`${Math.floor(minutes/60)} hr`;return`${Math.floor(minutes/1440)} d`;}
