"use client";
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";import type{CartItem}from"@/lib/cart/cart";import{cartTotal,normalizeQuantity}from"@/lib/cart/cart";
export default function CartPage(){
 const router=useRouter(),[items,setItems]=useState<CartItem[]>([]),[address,setAddress]=useState(""),[error,setError]=useState<string|null>(null),[pending,setPending]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>setItems(JSON.parse(localStorage.getItem("buildmate-cart")??"[]")),0);return()=>clearTimeout(timer)},[]);
 function save(next:CartItem[]){setItems(next);localStorage.setItem("buildmate-cart",JSON.stringify(next))}
 async function checkout(){setPending(true);setError(null);const r=await fetch("/api/cart/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items,address})});const result=await r.json();if(!r.ok){setError(result.error);setPending(false);if(r.status===401)router.push("/login?redirect=/cart");return}localStorage.removeItem("buildmate-cart");router.push("/dashboard/orders")}
 return <section className="container-shell py-12"><h1 className="text-4xl font-black">Your cart</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="card divide-y">{items.map(item=><div className="grid gap-3 p-5 md:grid-cols-[1fr_auto_auto]" key={item.listingId}><div><b>{item.name}</b><p className="text-sm text-slate-500">{item.supplier} · GHS {item.price.toFixed(2)}/{item.unit}</p></div><input className="input w-24" type="number" min="1" value={item.quantity} onChange={e=>save(items.map(x=>x.listingId===item.listingId?{...x,quantity:normalizeQuantity(Number(e.target.value))}:x))}/><button className="text-sm font-semibold text-red-600" onClick={()=>save(items.filter(x=>x.listingId!==item.listingId))}>Remove</button></div>)}{items.length===0&&<p className="p-8 text-center text-slate-500">Your cart is empty.</p>}</div><aside className="card h-fit p-6"><div className="flex justify-between text-xl font-black"><span>Total</span><span>GHS {cartTotal(items).toFixed(2)}</span></div><label className="mt-5 block"><span className="label">Delivery address</span><textarea className="input" value={address} onChange={e=>setAddress(e.target.value)} required/></label>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button className="btn-primary mt-5 w-full" disabled={pending||items.length===0} onClick={checkout}>{pending?"Creating orders...":"Checkout"}</button><p className="mt-3 text-xs text-slate-500">Orders are split by supplier and repriced securely at checkout.</p></aside></div></section>
}
