-- Resolve issues found by linked plpgsql_check without altering applied migrations.
create or replace function public.admin_list_customers(search_text text default null,role_filter text default null,status_filter text default null,region_filter text default null,registered_from date default null,registered_to date default null,min_spend numeric default null,sort_by text default 'newest',page_number integer default 1,page_size integer default 25)
returns table(id uuid,full_name text,email text,phone text,account_type text,organisation text,region text,registered_at timestamptz,order_count bigint,total_spent numeric,active_projects bigint,last_activity timestamptz,account_status text,verification_status text,total_rows bigint)
language plpgsql stable security definer set search_path=public,auth as $$
#variable_conflict use_column
begin
 if not public.admin_has_permission('customer_support') then raise exception 'Not authorised'; end if;
 return query with base as(
  select p.id,p.full_name,u.email,p.phone,p.role::text account_type,orgs.organisation,addr.region,p.created_at,coalesce(ord.order_count,0) order_count,coalesce(ord.total_spent,0) total_spent,coalesce(proj.active_projects,0) active_projects,coalesce(p.last_activity_at,u.last_sign_in_at) last_activity,p.account_status,p.verification_status
  from profiles p join auth.users u on u.id=p.id
  left join lateral(select string_agg(o.name,', ' order by o.name) organisation from organisation_members om join organisations o on o.id=om.organisation_id where om.user_id=p.id and om.is_active)orgs on true
  left join lateral(select a.region from addresses a where a.user_id=p.id order by a.is_default desc,a.created_at desc limit 1)addr on true
  left join lateral(select count(*) order_count,coalesce(sum(total)filter(where status<>'cancelled'),0) total_spent from orders where customer_id=p.id)ord on true
  left join lateral(select count(*) active_projects from projects where owner_id=p.id and status='active')proj on true where p.role in('customer','contractor','professional')),
 filtered as(select base.*,count(*)over() total_rows from base where(search_text is null or base.full_name ilike '%'||search_text||'%' or base.email ilike '%'||search_text||'%' or base.phone ilike '%'||search_text||'%')and(role_filter is null or base.account_type=role_filter)and(status_filter is null or base.account_status=status_filter)and(region_filter is null or base.region=region_filter)and(registered_from is null or base.created_at::date>=registered_from)and(registered_to is null or base.created_at::date<=registered_to)and(min_spend is null or base.total_spent>=min_spend))
 select f.id,f.full_name,f.email,f.phone,f.account_type,f.organisation,f.region,f.created_at,f.order_count,f.total_spent,f.active_projects,f.last_activity,f.account_status,f.verification_status,f.total_rows from filtered f order by case when sort_by='oldest' then f.created_at end asc,case when sort_by='highest_spending' then f.total_spent end desc,case when sort_by='most_orders' then f.order_count end desc,f.created_at desc offset greatest(page_number-1,0)*least(greatest(page_size,1),100) limit least(greatest(page_size,1),100);
end;$$;

create or replace function public.admin_list_suppliers_v2(search_text text default null,status_filter text default null,verification_level_filter text default null,region_filter text default null,category_filter text default null,performance_filter text default null,registered_from date default null,registered_to date default null,sort_by text default 'newest',page_number integer default 1,page_size integer default 25)
returns table(id uuid,business_name text,trading_name text,primary_contact text,phone text,email text,business_type text,region text,categories text[],verification_status text,verification_levels text[],product_count bigint,order_count bigint,total_sales numeric,fulfilment_rate numeric,average_rating numeric,settlement_status text,account_status text,registered_at timestamptz,performance_rating text,total_rows bigint)
language plpgsql stable security definer set search_path=public as $$
#variable_conflict use_column
begin
 if not public.admin_has_permission('supplier_verification') then raise exception 'Not authorised'; end if;
 return query with base as(select o.id,o.name business_name,sp.trading_name,sp.primary_contact_name,sp.primary_phone,sp.business_email,sp.business_type::text,sp.region,sp.primary_categories,o.verification_status::text,o.verification_levels::text[],coalesce(l.product_count,0) product_count,coalesce(m.order_count,0)::bigint order_count,coalesce(s.total_sales,0) total_sales,coalesce(m.fulfilment_rate,0) fulfilment_rate,coalesce(m.average_rating,0) average_rating,case when o.settlement_hold then 'held' when sd.organisation_id is null then 'missing' else 'ready' end settlement_status,o.account_status,o.created_at,coalesce(m.rating,'needs_attention') performance_rating from organisations o left join supplier_profiles sp on sp.organisation_id=o.id left join supplier_settlement_details sd on sd.organisation_id=o.id left join supplier_performance_metrics m on m.supplier_id=o.id left join lateral(select count(*) product_count from supplier_listings where supplier_id=o.id)l on true left join lateral(select coalesce(sum(total),0) total_sales from orders where supplier_id=o.id and status not in('cancelled','refunded'))s on true where o.organisation_type='supplier'),
 filtered as(select base.*,count(*)over() total_rows from base where(search_text is null or base.business_name ilike '%'||search_text||'%' or base.trading_name ilike '%'||search_text||'%' or base.primary_contact_name ilike '%'||search_text||'%' or base.business_email ilike '%'||search_text||'%')and(status_filter is null or base.verification_status=status_filter or base.account_status=status_filter)and(verification_level_filter is null or verification_level_filter=any(base.verification_levels))and(region_filter is null or base.region=region_filter)and(category_filter is null or category_filter=any(base.primary_categories))and(performance_filter is null or base.performance_rating=performance_filter)and(registered_from is null or base.created_at::date>=registered_from)and(registered_to is null or base.created_at::date<=registered_to))
 select f.id,f.business_name,f.trading_name,f.primary_contact_name,f.primary_phone,f.business_email,f.business_type,f.region,f.primary_categories,f.verification_status,f.verification_levels,f.product_count,f.order_count,f.total_sales,f.fulfilment_rate,f.average_rating,f.settlement_status,f.account_status,f.created_at,f.performance_rating,f.total_rows from filtered f order by case when sort_by='oldest' then f.created_at end asc,case when sort_by='highest_sales' then f.total_sales end desc,case when sort_by='most_orders' then f.order_count end desc,f.created_at desc offset greatest(page_number-1,0)*least(greatest(page_size,1),100) limit least(greatest(page_size,1),100);
end;$$;

create or replace function public.admin_list_suppliers(search_text text default null,status_filter text default null,region_filter text default null,category_filter text default null,performance_filter text default null,sort_by text default 'newest',page_number integer default 1,page_size integer default 25)
returns table(id uuid,business_name text,trading_name text,primary_contact text,phone text,email text,business_type text,region text,categories text[],verification_status text,verification_levels text[],product_count bigint,order_count bigint,total_sales numeric,fulfilment_rate numeric,average_rating numeric,settlement_status text,account_status text,registered_at timestamptz,performance_rating text,total_rows bigint)
language sql stable security definer set search_path=public as $$select * from public.admin_list_suppliers_v2(search_text,status_filter,null,region_filter,category_filter,performance_filter,null,null,sort_by,page_number,page_size)$$;

create or replace function public.admin_assign_delivery(target_delivery uuid,target_driver uuid,target_vehicle text,target_otp text)returns void language plpgsql security definer set search_path=public,extensions as $$begin if not public.admin_has_permission('logistics')then raise exception'Logistics permission required';end if;if not exists(select 1 from profiles where id=target_driver and role='driver')then raise exception'Driver account required';end if;update deliveries set driver_id=target_driver,vehicle_registration=target_vehicle,otp_hash=extensions.crypt(target_otp,extensions.gen_salt('bf')),status='driver_assigned',assigned_at=now(),updated_at=now()where id=target_delivery and status='pending_assignment';if not found then raise exception'Delivery cannot be assigned';end if;update orders set status='driver_assigned',updated_at=now()where id=(select order_id from deliveries where id=target_delivery);end;$$;
create or replace function public.driver_complete_delivery(target_delivery uuid,target_otp text,target_proofs text[])returns void language plpgsql security definer set search_path=public,extensions as $$declare order_target uuid;begin update deliveries set status='delivered',proof_urls=target_proofs,otp_verified_at=now(),delivered_at=now(),updated_at=now() where id=target_delivery and driver_id=auth.uid() and status='in_transit' and otp_hash=extensions.crypt(target_otp,otp_hash) and cardinality(target_proofs)>0 returning order_id into order_target;if order_target is null then raise exception'OTP is invalid or proof is missing';end if;update orders set status='customer_confirmation_pending',updated_at=now()where id=order_target;end;$$;

create or replace function public.checkout_cart(cart_items jsonb,target_address text) returns uuid[] language plpgsql security definer set search_path=public as $$
declare supplier uuid;new_order uuid;result uuid[]:='{}'::uuid[];subtotal_value numeric;item jsonb;listing record;
begin if auth.uid() is null then raise exception 'Sign in required';end if;if length(trim(target_address))<3 then raise exception 'Delivery address required';end if;if jsonb_array_length(cart_items)=0 or jsonb_array_length(cart_items)>100 then raise exception 'Cart is empty or too large';end if;
for supplier in select distinct l.supplier_id from jsonb_array_elements(cart_items)i join public.supplier_listings l on l.id=(i->>'listing_id')::uuid where l.is_active loop select sum(l.price*(i->>'quantity')::numeric) into subtotal_value from jsonb_array_elements(cart_items)i join public.supplier_listings l on l.id=(i->>'listing_id')::uuid where l.supplier_id=supplier and l.is_active and (i->>'quantity')::numeric>0;insert into public.orders(order_number,customer_id,supplier_id,status,subtotal,delivery_address) values('BM-'||to_char(now(),'YYYYMMDD')||'-'||lpad(nextval('public.order_number_seq')::text,6,'0'),auth.uid(),supplier,'awaiting_payment',subtotal_value,target_address) returning id into new_order;for item in select * from jsonb_array_elements(cart_items) loop select l.id,l.price,p.name,p.base_unit into listing from public.supplier_listings l join public.products p on p.id=l.product_id where l.id=(item->>'listing_id')::uuid and l.supplier_id=supplier and l.is_active for update;if found and (item->>'quantity')::numeric>0 then insert into public.order_items(order_id,listing_id,product_name_snapshot,quantity,unit,unit_price) values(new_order,listing.id,listing.name,(item->>'quantity')::numeric,listing.base_unit,listing.price);end if;end loop;result=array_append(result,new_order);end loop;if cardinality(result)=0 then raise exception 'No available listings in cart';end if;return result;end;$$;
