-- Enforce scoped permissions and account trading restrictions at the database boundary.
create or replace function public.enforce_customer_trading_status()returns trigger language plpgsql security definer set search_path=public as $$declare status text;customer uuid;begin customer=coalesce((to_jsonb(new)->>'customer_id')::uuid,(to_jsonb(new)->>'requester_id')::uuid);select account_status into status from profiles where id=customer;if status is distinct from'active'then raise exception'Account is not permitted to transact';end if;return new;end;$$;
create trigger order_customer_status_guard before insert on public.orders for each row execute function public.enforce_customer_trading_status();
create trigger rfq_customer_status_guard before insert on public.quote_requests for each row execute function public.enforce_customer_trading_status();
create or replace function public.enforce_supplier_publishing()returns trigger language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from organisations where id=new.supplier_id and account_status='active'and product_publishing_enabled and verification_status='approved')then raise exception'Supplier publishing is restricted';end if;return new;end;$$;
create trigger supplier_listing_publish_guard before insert or update of is_active,price,stock_quantity,stock_status on public.supplier_listings for each row execute function public.enforce_supplier_publishing();

create or replace function public.supplier_progress_order(target_order uuid,new_status public.order_status)returns void language plpgsql security definer set search_path=public as $$declare current_status public.order_status;begin select status into current_status from orders where id=target_order and public.is_org_member(supplier_id)and exists(select 1 from organisations org where org.id=orders.supplier_id and org.account_status='active'and org.order_acceptance_enabled)for update;if current_status is null then raise exception'Order not found or supplier acceptance is restricted';end if;if not((current_status='paid'and new_status='confirmed')or(current_status='confirmed'and new_status='preparing')or(current_status='preparing'and new_status='ready_for_dispatch'))then raise exception'Invalid order transition';end if;update orders set status=new_status,updated_at=now()where id=target_order;end;$$;

create or replace function public.admin_set_supplier_status(target_org uuid,new_status public.supplier_verification_status,reason text default null,new_verification_levels public.supplier_verification_level[]default null)returns void language plpgsql security definer set search_path=public as $$declare current_status public.supplier_verification_status;begin if not public.admin_has_permission('supplier_verification')then raise exception'Not authorised';end if;if new_status in('rejected','information_required','suspended','approved')and length(trim(coalesce(reason,'')))<5 then raise exception'A detailed reason is required';end if;select verification_status into current_status from organisations where id=target_org;if current_status is null then raise exception'organisation not found';end if;if not public.is_valid_supplier_transition(current_status,new_status)then raise exception'cannot move supplier from % to %',current_status,new_status;end if;update organisations set verification_status=new_status,decision_reason=case when new_status in('rejected','information_required')then reason else null end,suspended_reason=case when new_status='suspended'then reason else suspended_reason end,reviewer_id=auth.uid(),reviewed_at=now(),approved_at=case when new_status='approved'then now()else approved_at end,suspended_at=case when new_status='suspended'then now()else suspended_at end,verification_levels=coalesce(new_verification_levels,verification_levels)where id=target_org;insert into supplier_review_events(organisation_id,actor_id,event_type,from_status,to_status,reason)values(target_org,auth.uid(),new_status::text,current_status,new_status,reason);insert into admin_action_history(actor_id,action,subject_type,subject_id,reason,before_data,after_data)values(auth.uid(),'supplier_verification_'||new_status,'supplier',target_org,trim(reason),jsonb_build_object('status',current_status),jsonb_build_object('status',new_status));end;$$;
create or replace function public.assign_supplier_reviewer(target_org uuid,reviewer uuid)returns void language plpgsql security definer set search_path=public as $$begin if not public.admin_has_permission('supplier_verification')then raise exception'Not authorised';end if;if not exists(select 1 from profiles where id=reviewer and role in('admin','super_admin'))then raise exception'Admin reviewer required';end if;update organisations set reviewer_id=reviewer where id=target_org and organisation_type='supplier';if not found then raise exception'Supplier not found';end if;insert into supplier_review_events(organisation_id,actor_id,event_type,metadata)values(target_org,auth.uid(),'reviewer_assigned',jsonb_build_object('reviewer_id',reviewer));insert into admin_action_history(actor_id,action,subject_type,subject_id,reason,metadata)values(auth.uid(),'supplier_reviewer_assigned','supplier',target_org,'Reviewer assignment',jsonb_build_object('reviewer_id',reviewer));end;$$;
create or replace function public.add_supplier_review_note(target_org uuid,note_text text)returns void language plpgsql security definer set search_path=public as $$begin if not public.admin_has_permission('supplier_verification')then raise exception'Not authorised';end if;if length(trim(note_text))<2 then raise exception'Note is required';end if;insert into supplier_review_notes(organisation_id,author_id,note)values(target_org,auth.uid(),trim(note_text));insert into supplier_review_events(organisation_id,actor_id,event_type)values(target_org,auth.uid(),'note_added');insert into admin_action_history(actor_id,action,subject_type,subject_id,reason)values(auth.uid(),'supplier_note_added','supplier',target_org,'Internal note added');end;$$;
create or replace function public.admin_mark_ledger_paid(target_entry uuid,payout_reference text)returns void language plpgsql security definer set search_path=public as $$begin if not public.admin_has_permission('finance')then raise exception'Finance permission required';end if;if length(trim(payout_reference))<3 then raise exception'Payout reference required';end if;update supplier_ledger_entries set status='paid',settled_at=now(),description=description||' · Payout '||payout_reference where id=target_entry and status='available'and not exists(select 1 from organisations o where o.id=supplier_id and o.settlement_hold);if not found then raise exception'Ledger entry is unavailable or settlement is held';end if;end;$$;
create or replace function public.admin_assign_delivery(target_delivery uuid,target_driver uuid,target_vehicle text,target_otp text)returns void language plpgsql security definer set search_path=public as $$begin if not public.admin_has_permission('logistics')then raise exception'Logistics permission required';end if;if not exists(select 1 from profiles where id=target_driver and role='driver')then raise exception'Driver account required';end if;update deliveries set driver_id=target_driver,vehicle_registration=target_vehicle,otp_hash=crypt(target_otp,gen_salt('bf')),status='driver_assigned',assigned_at=now(),updated_at=now()where id=target_delivery and status='pending_assignment';if not found then raise exception'Delivery cannot be assigned';end if;update orders set status='driver_assigned',updated_at=now()where id=(select order_id from deliveries where id=target_delivery);end;$$;

drop policy if exists "admin reconciliation manage" on public.reconciliation_runs;create policy "finance reconciliation manage" on public.reconciliation_runs for all using(public.admin_has_permission('finance'))with check(public.admin_has_permission('finance'));
drop policy if exists "catalogue admin categories" on public.categories;create policy "catalogue scoped categories" on public.categories for all using(public.admin_has_permission('catalogue'))with check(public.admin_has_permission('catalogue'));
drop policy if exists "catalogue admin brands" on public.brands;create policy "catalogue scoped brands" on public.brands for all using(public.admin_has_permission('catalogue'))with check(public.admin_has_permission('catalogue'));
drop policy if exists "catalogue admin products" on public.products;create policy "catalogue scoped products" on public.products for all using(public.admin_has_permission('catalogue'))with check(public.admin_has_permission('catalogue'));

revoke all on function public.admin_set_supplier_status(uuid,public.supplier_verification_status,text,public.supplier_verification_level[]),public.assign_supplier_reviewer(uuid,uuid),public.add_supplier_review_note(uuid,text),public.admin_mark_ledger_paid(uuid,text),public.admin_assign_delivery(uuid,uuid,text,text)from public,anon;
grant execute on function public.admin_set_supplier_status(uuid,public.supplier_verification_status,text,public.supplier_verification_level[]),public.assign_supplier_reviewer(uuid,uuid),public.add_supplier_review_note(uuid,text),public.admin_mark_ledger_paid(uuid,text),public.admin_assign_delivery(uuid,uuid,text,text)to authenticated;
