-- Phase 9: durable, retryable multi-channel notification outbox.
create table public.notification_preferences(user_id uuid primary key references public.profiles(id) on delete cascade,email_enabled boolean not null default true,sms_enabled boolean not null default true,whatsapp_enabled boolean not null default false,updated_at timestamptz not null default now());
create table public.notification_outbox(id uuid primary key default gen_random_uuid(),recipient_user_id uuid references public.profiles(id),recipient_email text,recipient_phone text,channel text not null check(channel in('email','sms','whatsapp')),template_key text not null,payload jsonb not null default '{}',status text not null default 'pending' check(status in('pending','processing','sent','failed')),attempts int not null default 0,next_attempt_at timestamptz not null default now(),provider_message_id text,last_error text,created_at timestamptz not null default now(),sent_at timestamptz);
alter table public.notification_preferences enable row level security;alter table public.notification_outbox enable row level security;
create policy "preference owner manage" on public.notification_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "notification owner read" on public.notification_outbox for select using(recipient_user_id=auth.uid());
create policy "notification admin read" on public.notification_outbox for select using(public.is_platform_admin());
create index idx_notification_pending on public.notification_outbox(status,next_attempt_at) where status in('pending','failed');

create or replace function public.enqueue_user_notification(target_user uuid,target_template text,target_payload jsonb,target_channel text default 'email') returns uuid language plpgsql security definer set search_path=public,auth as $$declare result uuid;target_email text;target_phone text;allowed boolean;begin select u.email,p.phone,case target_channel when 'email' then coalesce(np.email_enabled,true) when 'sms' then coalesce(np.sms_enabled,true) else coalesce(np.whatsapp_enabled,false) end into target_email,target_phone,allowed from auth.users u join public.profiles p on p.id=u.id left join public.notification_preferences np on np.user_id=u.id where u.id=target_user;if not allowed then return null;end if;insert into public.notification_outbox(recipient_user_id,recipient_email,recipient_phone,channel,template_key,payload) values(target_user,target_email,target_phone,target_channel,target_template,target_payload) returning id into result;return result;end;$$;
revoke all on function public.enqueue_user_notification(uuid,text,jsonb,text) from public,anon,authenticated;

create or replace function public.notify_quote_response() returns trigger language plpgsql security definer set search_path=public as $$declare target uuid;begin select requester_id into target from public.quote_requests where id=new.quote_request_id;perform public.enqueue_user_notification(target,'quote_received',jsonb_build_object('quote_id',new.id,'request_id',new.quote_request_id,'total',new.total));return new;end;$$;
create trigger supplier_quote_notification after insert on public.supplier_quotes for each row execute function public.notify_quote_response();
create or replace function public.notify_delivery_assignment() returns trigger language plpgsql security definer set search_path=public as $$begin if new.driver_id is not null and old.driver_id is distinct from new.driver_id then perform public.enqueue_user_notification(new.driver_id,'delivery_assigned',jsonb_build_object('delivery_id',new.id,'location',new.delivery_location));end if;return new;end;$$;
create trigger delivery_assignment_notification after update on public.deliveries for each row execute function public.notify_delivery_assignment();
