alter table public.quote_requests add column organisation_id uuid references public.organisations(id),add column requested_by_membership_id uuid references public.organisation_members(id);
alter table public.orders add column customer_organisation_id uuid references public.organisations(id),add column created_by_membership_id uuid references public.organisation_members(id),add column approval_status text not null default 'not_required' check(approval_status in('not_required','pending','approved','rejected'));
create index idx_orders_customer_org on public.orders(customer_organisation_id,created_at desc);create index idx_quote_requests_customer_org on public.quote_requests(organisation_id,created_at desc);

create table public.purchase_requests(id uuid primary key default gen_random_uuid(),organisation_id uuid not null references public.organisations(id),project_id uuid references public.projects(id),requester_membership_id uuid not null references public.organisation_members(id),title text not null,description text,estimated_amount numeric(14,2)not null check(estimated_amount>=0),status text not null default 'submitted' check(status in('draft','submitted','project_reviewed','budget_checked','approved','rejected','ordered')),current_stage text not null default 'project_review' check(current_stage in('project_review','budget_check','authorisation','procurement','complete')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.purchase_request_approvals(id uuid primary key default gen_random_uuid(),purchase_request_id uuid not null references public.purchase_requests(id)on delete cascade,actor_membership_id uuid not null references public.organisation_members(id),stage text not null,decision text not null check(decision in('approved','rejected')),notes text,created_at timestamptz not null default now());
alter table public.purchase_requests enable row level security;alter table public.purchase_request_approvals enable row level security;
create policy "organisation purchase request read"on public.purchase_requests for select using(public.has_permission('organisation.view',organisation_id));
create policy "organisation approval read"on public.purchase_request_approvals for select using(exists(select 1 from purchase_requests r where r.id=purchase_request_id and public.has_permission('organisation.view',r.organisation_id)));
revoke insert,update,delete on public.purchase_requests,public.purchase_request_approvals from anon,authenticated;

create or replace function public.customer_can_read_order(target public.orders)returns boolean language sql stable security definer set search_path=public as $$select target.customer_id=auth.uid() or(target.customer_organisation_id is not null and public.has_permission('organisation.view',target.customer_organisation_id))$$;
create or replace function public.customer_can_read_quote_request(target public.quote_requests)returns boolean language sql stable security definer set search_path=public as $$select target.requester_id=auth.uid() or(target.organisation_id is not null and public.has_permission('quotations.view',target.organisation_id))$$;

drop policy if exists "customer order read"on public.orders;create policy "customer order read"on public.orders for select using(public.customer_can_read_order(orders));
drop policy if exists "order supplier read"on public.orders;create policy "order supplier read"on public.orders for select using(public.has_permission('orders.view',supplier_id));
drop policy if exists "order items participant read"on public.order_items;create policy "order items participant read"on public.order_items for select using(exists(select 1 from orders o where o.id=order_id and(public.customer_can_read_order(o)or public.has_permission('orders.view',o.supplier_id)or public.is_platform_admin())));
drop policy if exists "quote participant read"on public.supplier_quotes;create policy "quote participant read"on public.supplier_quotes for select using(public.has_permission('quotations.view',supplier_id)or exists(select 1 from quote_requests r where r.id=quote_request_id and public.customer_can_read_quote_request(r))or public.is_platform_admin());
drop policy if exists "supplier create quote"on public.supplier_quotes;create policy "supplier create quote"on public.supplier_quotes for insert with check(public.has_permission('quotations.submit',supplier_id));
drop policy if exists "supplier update quote"on public.supplier_quotes;create policy "supplier update quote"on public.supplier_quotes for update using(public.has_permission('quotations.submit',supplier_id))with check(public.has_permission('quotations.submit',supplier_id));
drop policy if exists "supplier listing member read"on public.supplier_listings;create policy "supplier listing member read"on public.supplier_listings for select using(public.has_permission('products.view',supplier_id)or public.is_platform_admin());
drop policy if exists "supplier listing member insert"on public.supplier_listings;create policy "supplier listing member insert"on public.supplier_listings for insert with check(public.has_permission('products.create',supplier_id)and exists(select 1 from organisations where id=supplier_id and verification_status='approved'));
drop policy if exists "supplier listing member update"on public.supplier_listings;create policy "supplier listing member update"on public.supplier_listings for update using(public.has_permission('products.edit',supplier_id)or public.is_platform_admin())with check(public.has_permission('products.edit',supplier_id)or public.is_platform_admin());
drop policy if exists "supplier listing member delete"on public.supplier_listings;create policy "supplier listing member delete"on public.supplier_listings for delete using(public.has_permission('products.edit',supplier_id)or public.is_platform_admin());
drop policy if exists "settlement read"on public.supplier_settlement_details;drop policy if exists "settlement owner or finance read"on public.supplier_settlement_details;create policy "settlement explicit permission read"on public.supplier_settlement_details for select using(public.has_permission('settlement_details.manage',organisation_id)or public.is_platform_admin());
drop policy if exists "settlement insert"on public.supplier_settlement_details;create policy "settlement explicit permission insert"on public.supplier_settlement_details for insert with check(public.has_permission('settlement_details.manage',organisation_id)and public.is_org_editable(organisation_id));
drop policy if exists "settlement update"on public.supplier_settlement_details;create policy "settlement explicit permission update"on public.supplier_settlement_details for update using(public.has_permission('settlement_details.manage',organisation_id))with check(public.has_permission('settlement_details.manage',organisation_id)and public.is_org_editable(organisation_id));
drop policy if exists "supplier documents storage read"on storage.objects;create policy "supplier documents permission read"on storage.objects for select using(bucket_id='supplier-documents'and(public.has_permission('supplier.profile.view',((storage.foldername(name))[1])::uuid)or public.is_platform_admin()));
drop policy if exists "supplier documents storage insert"on storage.objects;create policy "supplier documents permission insert"on storage.objects for insert with check(bucket_id='supplier-documents'and public.has_permission('supplier.profile.edit',((storage.foldername(name))[1])::uuid)and public.is_org_editable(((storage.foldername(name))[1])::uuid));
drop policy if exists "supplier documents storage delete"on storage.objects;create policy "supplier documents permission delete"on storage.objects for delete using(bucket_id='supplier-documents'and public.has_permission('supplier.profile.edit',((storage.foldername(name))[1])::uuid)and public.is_org_editable(((storage.foldername(name))[1])::uuid));

create or replace function public.checkout_cart_for_context(cart_items jsonb,target_address text,target_customer_organisation uuid default null)returns uuid[] language plpgsql security definer set search_path=public as $$
declare supplier uuid;new_order uuid;result uuid[]:='{}';subtotal_value numeric;item jsonb;listing record;member_id uuid;
begin if auth.uid()is null then raise exception 'Sign in required';end if;if target_customer_organisation is not null then if not has_permission('orders.create',target_customer_organisation)then raise exception 'Order creation permission required';end if;select id into member_id from organisation_members where organisation_id=target_customer_organisation and user_id=auth.uid()and status='active'and is_active;end if;if length(trim(target_address))<3 then raise exception 'Delivery address required';end if;if jsonb_array_length(cart_items)=0 or jsonb_array_length(cart_items)>100 then raise exception 'Cart is empty or too large';end if;for supplier in select distinct l.supplier_id from jsonb_array_elements(cart_items)i join supplier_listings l on l.id=(i->>'listing_id')::uuid where l.is_active loop select sum(l.price*(i->>'quantity')::numeric)into subtotal_value from jsonb_array_elements(cart_items)i join supplier_listings l on l.id=(i->>'listing_id')::uuid where l.supplier_id=supplier and l.is_active and(i->>'quantity')::numeric>0;insert into orders(order_number,customer_id,customer_organisation_id,created_by_membership_id,supplier_id,status,subtotal,delivery_address)values('BM-'||to_char(now(),'YYYYMMDD')||'-'||lpad(nextval('order_number_seq')::text,6,'0'),auth.uid(),target_customer_organisation,member_id,supplier,'awaiting_payment',subtotal_value,target_address)returning id into new_order;for item in select * from jsonb_array_elements(cart_items)loop select l.id,l.price,p.name,p.base_unit into listing from supplier_listings l join products p on p.id=l.product_id where l.id=(item->>'listing_id')::uuid and l.supplier_id=supplier and l.is_active for update;if found and(item->>'quantity')::numeric>0 then insert into order_items(order_id,listing_id,product_name_snapshot,quantity,unit,unit_price)values(new_order,listing.id,listing.name,(item->>'quantity')::numeric,listing.base_unit,listing.price);end if;end loop;result:=array_append(result,new_order);end loop;if cardinality(result)=0 then raise exception 'No available listings in cart';end if;return result;end;$$;
grant execute on function public.checkout_cart_for_context(jsonb,text,uuid)to authenticated;

create or replace function public.submit_purchase_request(target_organisation uuid,target_project uuid,target_title text,target_description text,target_amount numeric)returns uuid language plpgsql security definer set search_path=public as $$declare member_id uuid;result uuid;begin if not has_permission('purchase_requests.create',target_organisation)then raise exception 'Not authorised';end if;select id into member_id from organisation_members where organisation_id=target_organisation and user_id=auth.uid()and status='active'and is_active;if target_project is not null and not exists(select 1 from projects where id=target_project and organisation_id=target_organisation)then raise exception 'Project belongs to another organisation';end if;insert into purchase_requests(organisation_id,project_id,requester_membership_id,title,description,estimated_amount)values(target_organisation,target_project,member_id,trim(target_title),nullif(trim(coalesce(target_description,'')),''),target_amount)returning id into result;insert into membership_audit_log(actor_id,scope,target_membership_id,target_user_id,organisation_id,action,after_data)values(auth.uid(),'customer',member_id,auth.uid(),target_organisation,'purchase_request_submitted',jsonb_build_object('purchase_request_id',result,'amount',target_amount));return result;end;$$;
create or replace function public.decide_purchase_request(target_request uuid,target_decision text,target_notes text)returns void language plpgsql security definer set search_path=public as $$declare r purchase_requests;member_id uuid;next_stage text;next_status text;limit_value numeric;begin select * into r from purchase_requests where id=target_request for update;if r.id is null then raise exception 'Request not found';end if;if not has_permission('purchase_requests.approve',r.organisation_id)then raise exception 'Not authorised';end if;select m.id,max(pm.approval_limit)into member_id,limit_value from organisation_members m left join project_memberships pm on pm.membership_id=m.id and(r.project_id is null or pm.project_id=r.project_id)where m.organisation_id=r.organisation_id and m.user_id=auth.uid()and m.status='active'and m.is_active group by m.id;if target_decision='approved'and limit_value is not null and r.estimated_amount>limit_value then raise exception 'Request exceeds your approval limit';end if;if target_decision not in('approved','rejected')then raise exception 'Invalid decision';end if;if target_decision='rejected'then next_status:='rejected';next_stage:=r.current_stage;elsif r.current_stage='project_review'then next_status:='project_reviewed';next_stage:='budget_check';elsif r.current_stage='budget_check'then next_status:='budget_checked';next_stage:='authorisation';elsif r.current_stage='authorisation'then next_status:='approved';next_stage:='procurement';else next_status:=r.status;next_stage:=r.current_stage;end if;insert into purchase_request_approvals(purchase_request_id,actor_membership_id,stage,decision,notes)values(r.id,member_id,r.current_stage,target_decision,nullif(trim(coalesce(target_notes,'')),''));update purchase_requests set status=next_status,current_stage=next_stage,updated_at=now()where id=r.id;end;$$;
grant execute on function public.submit_purchase_request(uuid,uuid,text,text,numeric),public.decide_purchase_request(uuid,text,text)to authenticated;
create or replace function public.begin_payment(target_order uuid,target_provider text)returns public.payments language plpgsql security definer set search_path=public as $$declare target public.orders;attempt public.payments;begin select * into target from orders where id=target_order for update;if target.customer_organisation_id is null then if target.customer_id<>auth.uid()then raise exception 'Not authorised';end if;elsif not has_permission('payments.initiate',target.customer_organisation_id)then raise exception 'Payment initiation permission required';end if;if target.status<>'awaiting_payment'then raise exception 'Order is not awaiting payment';end if;insert into payments(order_id,provider,amount,currency,status,idempotency_key)values(target.id,target_provider,target.total,'GHS','pending',target_provider||':'||target.id)on conflict(idempotency_key)do update set updated_at=now()returning * into attempt;return attempt;end;$$;
create or replace function public.accept_supplier_quote(target_quote uuid)returns uuid language plpgsql security definer set search_path=public as $$declare q supplier_quotes;r quote_requests;new_order uuid;snapshot_name text;member_id uuid;begin select * into q from supplier_quotes where id=target_quote for update;if q.id is null or q.status<>'responded'then raise exception 'Quotation is unavailable';end if;select * into r from quote_requests where id=q.quote_request_id for update;if r.organisation_id is null then if r.requester_id<>auth.uid()then raise exception 'Not authorised';end if;elsif not has_permission('quotations.accept',r.organisation_id)or not has_permission('orders.create',r.organisation_id)then raise exception 'Quote acceptance and order creation permissions required';else select id into member_id from organisation_members where organisation_id=r.organisation_id and user_id=auth.uid()and status='active'and is_active;end if;if r.status<>'open'then raise exception 'Request is no longer open';end if;select string_agg(description,'; 'order by id)into snapshot_name from quote_request_items where quote_request_id=r.id;insert into orders(order_number,customer_id,customer_organisation_id,created_by_membership_id,project_id,supplier_id,quote_id,status,subtotal,delivery_fee,delivery_address)values('BM-'||to_char(now(),'YYYYMMDD')||'-'||lpad(nextval('order_number_seq')::text,6,'0'),auth.uid(),r.organisation_id,member_id,r.project_id,q.supplier_id,q.id,'awaiting_payment',q.subtotal,q.delivery_fee,r.delivery_location)returning id into new_order;insert into order_items(order_id,product_name_snapshot,quantity,unit,unit_price)values(new_order,coalesce(snapshot_name,r.title),1,'quotation',q.subtotal);update supplier_quotes set status=case when id=q.id then'accepted'::quote_status else'rejected'::quote_status end where quote_request_id=r.id;update quote_requests set status='accepted'where id=r.id;insert into audit_logs(actor_id,entity_type,entity_id,action,after_data)values(auth.uid(),'order',new_order::text,'created_from_quote',jsonb_build_object('quote_id',q.id,'customer_organisation_id',r.organisation_id));return new_order;end;$$;
