-- Server-side administrative reporting. These functions expose shaped records
-- only after scoped permission checks; auth.users is never directly exposed.
alter table public.supplier_performance_metrics
 add column acceptance_time_score numeric(5,2) not null default 50,
 add column quotation_response_score numeric(5,2) not null default 50,
 add column return_rate numeric(5,2) not null default 0,
 add column stock_update_score numeric(5,2) not null default 50,
 add column product_accuracy_score numeric(5,2) not null default 100;

create or replace function public.admin_overview_metrics() returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare result jsonb;begin if not public.admin_has_permission('viewer')then raise exception 'Not authorised';end if;
select jsonb_build_object(
 'total_customers',(select count(*) from profiles where role in('customer','contractor','professional')),
 'active_customers',(select count(*) from profiles where role in('customer','contractor','professional') and account_status='active'),
 'new_customers_month',(select count(*) from profiles where role in('customer','contractor','professional') and created_at>=date_trunc('month',now())),
 'total_suppliers',(select count(*) from organisations where organisation_type='supplier'),
 'approved_suppliers',(select count(*) from organisations where organisation_type='supplier' and verification_status='approved'),
 'pending_suppliers',(select count(*) from organisations where organisation_type='supplier' and verification_status in('submitted','under_review')),
 'suspended_suppliers',(select count(*) from organisations where organisation_type='supplier' and (verification_status='suspended' or account_status='suspended')),
 'total_orders',(select count(*) from orders),'orders_in_progress',(select count(*) from orders where status not in('completed','cancelled','refunded')),
 'completed_orders',(select count(*) from orders where status='completed'),'gmv',(select coalesce(sum(total),0) from orders where status not in('cancelled')),
 'platform_revenue',(select coalesce(sum(service_fee),0) from orders where status not in('cancelled','refunded')),
 'pending_settlements',(select coalesce(sum(amount),0) from supplier_ledger_entries where status in('pending','available')),
 'open_disputes',(select count(*) from order_disputes where status in('open','under_review')),
 'customer_registrations',(select coalesce(jsonb_agg(x order by x.bucket),'[]') from(select date_trunc('month',created_at)::date bucket,count(*) value from profiles where role in('customer','contractor','professional') group by 1 order by 1 desc limit 12)x),
 'supplier_registrations',(select coalesce(jsonb_agg(x order by x.bucket),'[]') from(select date_trunc('month',created_at)::date bucket,count(*) value from organisations where organisation_type='supplier' group by 1 order by 1 desc limit 12)x),
 'orders_over_time',(select coalesce(jsonb_agg(x order by x.bucket),'[]') from(select date_trunc('month',created_at)::date bucket,count(*) value from orders group by 1 order by 1 desc limit 12)x),
 'sales_over_time',(select coalesce(jsonb_agg(x order by x.bucket),'[]') from(select date_trunc('month',created_at)::date bucket,coalesce(sum(total),0) value from orders where status not in('cancelled','refunded') group by 1 order by 1 desc limit 12)x),
 'fulfilment_rate',(select case when count(*)=0 then 0 else round(100.0*count(*)filter(where status='completed')/count(*),2)end from orders),
 'repeat_purchase_rate',(select case when count(*)=0 then 0 else round(100.0*count(*)filter(where order_count>1)/count(*),2)end from(select customer_id,count(*)order_count from orders group by customer_id)c)
) into result;return result;end;$$;

create or replace function public.admin_list_customers(search_text text default null,role_filter text default null,status_filter text default null,region_filter text default null,registered_from date default null,registered_to date default null,min_spend numeric default null,sort_by text default 'newest',page_number integer default 1,page_size integer default 25)
returns table(id uuid,full_name text,email text,phone text,account_type text,organisation text,region text,registered_at timestamptz,order_count bigint,total_spent numeric,active_projects bigint,last_activity timestamptz,account_status text,verification_status text,total_rows bigint) language plpgsql stable security definer set search_path=public,auth as $$
begin if not public.admin_has_permission('customer_support')then raise exception 'Not authorised';end if;return query
with base as(select p.id,p.full_name,u.email,p.phone,p.role::text account_type,orgs.organisation,addr.region,p.created_at,coalesce(ord.order_count,0)order_count,coalesce(ord.total_spent,0)total_spent,coalesce(proj.active_projects,0)active_projects,coalesce(p.last_activity_at,u.last_sign_in_at)last_activity,p.account_status,p.verification_status from profiles p join auth.users u on u.id=p.id left join lateral(select string_agg(o.name,', 'order by o.name)organisation from organisation_members om join organisations o on o.id=om.organisation_id where om.user_id=p.id and om.is_active)orgs on true left join lateral(select a.region from addresses a where a.user_id=p.id order by a.is_default desc,a.created_at desc limit 1)addr on true left join lateral(select count(*)order_count,coalesce(sum(total)filter(where status<>'cancelled'),0)total_spent from orders where customer_id=p.id)ord on true left join lateral(select count(*)active_projects from projects where owner_id=p.id and status='active')proj on true where p.role in('customer','contractor','professional')),filtered as(select *,count(*)over() total_rows from base where(search_text is null or full_name ilike '%'||search_text||'%' or email ilike '%'||search_text||'%' or phone ilike '%'||search_text||'%')and(role_filter is null or account_type=role_filter)and(status_filter is null or account_status=status_filter)and(region_filter is null or region=region_filter)and(registered_from is null or created_at::date>=registered_from)and(registered_to is null or created_at::date<=registered_to)and(min_spend is null or total_spent>=min_spend))select f.id,f.full_name,f.email,f.phone,f.account_type,f.organisation,f.region,f.created_at,f.order_count,f.total_spent,f.active_projects,f.last_activity,f.account_status,f.verification_status,f.total_rows from filtered f order by case when sort_by='oldest' then f.created_at end asc,case when sort_by='highest_spending' then f.total_spent end desc,case when sort_by='most_orders' then f.order_count end desc,f.created_at desc offset greatest(page_number-1,0)*least(greatest(page_size,1),100) limit least(greatest(page_size,1),100);end;$$;

create or replace function public.admin_customer_detail(target_customer uuid) returns jsonb language plpgsql stable security definer set search_path=public,auth as $$
declare result jsonb;begin if not public.admin_has_permission('customer_support')then raise exception 'Not authorised';end if;select jsonb_build_object('profile',jsonb_build_object('id',p.id,'full_name',p.full_name,'email',u.email,'phone',p.phone,'alternative_phone',p.alternative_phone,'account_type',p.role,'registered_at',p.created_at,'last_activity',coalesce(p.last_activity_at,u.last_sign_in_at),'account_status',p.account_status,'verification_status',p.verification_status),'addresses',(select coalesce(jsonb_agg(a order by a.is_default desc),'[]')from addresses a where a.user_id=p.id),'orders',(select coalesce(jsonb_agg(o order by o.created_at desc),'[]')from orders o where o.customer_id=p.id),'quotes',(select coalesce(jsonb_agg(q order by q.created_at desc),'[]')from quote_requests q where q.requester_id=p.id),'projects',(select coalesce(jsonb_agg(pr order by pr.created_at desc),'[]')from projects pr where pr.owner_id=p.id),'payments',(select coalesce(jsonb_agg(pay order by pay.created_at desc),'[]')from payments pay join orders o on o.id=pay.order_id where o.customer_id=p.id),'deliveries',(select coalesce(jsonb_agg(d order by d.created_at desc),'[]')from deliveries d join orders o on o.id=d.order_id where o.customer_id=p.id),'disputes',(select coalesce(jsonb_agg(di order by di.created_at desc),'[]')from order_disputes di where di.customer_id=p.id),'reviews',(select coalesce(jsonb_agg(r order by r.created_at desc),'[]')from reviews r where r.reviewer_id=p.id),'memberships',(select coalesce(jsonb_agg(jsonb_build_object('organisation_id',om.organisation_id,'name',org.name,'role',om.member_role,'active',om.is_active)),'[]')from organisation_members om join organisations org on org.id=om.organisation_id where om.user_id=p.id),'financial',jsonb_build_object('total_spent',(select coalesce(sum(total),0)from orders where customer_id=p.id and status not in('cancelled')),'total_refunds',(select coalesce(sum(amount),0)from payments pay join orders o on o.id=pay.order_id where o.customer_id=p.id and pay.status='refunded'),'outstanding',(select coalesce(sum(total),0)from orders where customer_id=p.id and status='awaiting_payment'),'average_order_value',(select coalesce(avg(total),0)from orders where customer_id=p.id),'completed_orders',(select count(*)from orders where customer_id=p.id and status='completed'),'cancelled_orders',(select count(*)from orders where customer_id=p.id and status='cancelled')),'notes',(select coalesce(jsonb_agg(n order by n.created_at desc),'[]')from admin_internal_notes n where n.subject_type='customer'and n.subject_id=p.id),'actions',(select coalesce(jsonb_agg(h order by h.created_at desc),'[]')from admin_action_history h where h.subject_type='customer'and h.subject_id=p.id))into result from profiles p join auth.users u on u.id=p.id where p.id=target_customer and p.role in('customer','contractor','professional');if result is null then raise exception 'Customer not found';end if;return result;end;$$;

revoke all on function public.admin_overview_metrics(),public.admin_list_customers(text,text,text,text,date,date,numeric,text,integer,integer),public.admin_customer_detail(uuid) from public,anon;
grant execute on function public.admin_overview_metrics(),public.admin_list_customers(text,text,text,text,date,date,numeric,text,integer,integer),public.admin_customer_detail(uuid) to authenticated;
